// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-X9YTsGRSWYRISkiVdAmhKtyUi2BtQGQ',
    appId: '1:892208382684:android:4245c1dff815546c2faa19',
    messagingSenderId: '892208382684',
    projectId: 'we-chat-8671a',
    databaseURL: 'https://we-chat-8671a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'we-chat-8671a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAckXqcBEd5-GyrLoAeBt0kXiKhV0cmMv8',
    appId: '1:892208382684:ios:8b2ac468e3f543082faa19',
    messagingSenderId: '892208382684',
    projectId: 'we-chat-8671a',
    databaseURL: 'https://we-chat-8671a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'we-chat-8671a.appspot.com',
    androidClientId: '892208382684-1ddhvkplda249g5dubkubb3cq3r8t0in.apps.googleusercontent.com',
    iosClientId: '892208382684-ec16so65npk5mpve245p98agt3i2ogj1.apps.googleusercontent.com',
    iosBundleId: 'com.example.wechat',
  );
}
